package FootballGame.Graphics;

import java.awt.image.BufferedImage;

/*! \class public class Assets
    \brief Clasa incarca fiecare element grafic necesar jocului.

    Game assets include tot ce este folosit intr-un joc: imagini, sunete, harti etc.
 */
public class Assets
{
        /// Referinte catre elementele grafice (dale) utilizate in joc.

    public static BufferedImage cursor;
    public static BufferedImage corner;
    public static BufferedImage goalNetLeft;
    public static BufferedImage goalNetLeft1;
    public static BufferedImage goalNetLeft2;
    public static BufferedImage goalNetLeft3;
    public static BufferedImage goalNetLeft4;
    public static BufferedImage goalNetLeft5;
    public static BufferedImage goalNetLeft6;
    public static BufferedImage goalNetLeft7;
    public static BufferedImage goalNetLeft8;
    public static BufferedImage goalNetLeft9;
    public static BufferedImage goalNetLeft10;
    public static BufferedImage goalNetLeft21;
    public static BufferedImage goalNetLeft22;
    public static BufferedImage goalNetLeft23;
    public static BufferedImage goalNetLeft24;
    public static BufferedImage goalNetLeft25;
    public static BufferedImage goalNetLeft26;
    public static BufferedImage goalNetLeft27;
    public static BufferedImage goalNetLeft28;

    public static BufferedImage controls;
    public static BufferedImage controlsEnter;
    public static BufferedImage graphicsSettings;
    public static BufferedImage graphicsHigh;
    public static BufferedImage graphicsLow;

    public static BufferedImage goalNetRight;
    public static BufferedImage goalNetRight1;
    public static BufferedImage goalNetRight2;
    public static BufferedImage goalNetRight3;
    public static BufferedImage goalNetRight4;
    public static BufferedImage goalNetRight5;
    public static BufferedImage goalNetRight6;
    public static BufferedImage goalNetRight7;
    public static BufferedImage goalNetRight8;
    public static BufferedImage goalNetRight9;
    public static BufferedImage goalNetRight10;
    public static BufferedImage goalNetRight21;
    public static BufferedImage goalNetRight22;
    public static BufferedImage goalNetRight23;
    public static BufferedImage goalNetRight24;
    public static BufferedImage goalNetRight25;
    public static BufferedImage goalNetRight26;
    public static BufferedImage goalNetRight27;
    public static BufferedImage goalNetRight28;

    public static BufferedImage P1_Arsenal;
    public static BufferedImage P1_Arsenal_Chelsea;
    public static BufferedImage P1_Arsenal_Chelsea_Reverse;
    public static BufferedImage P1_Arsenal_Enter;
    public static BufferedImage P1_Arsenal_Enter2;
    public static BufferedImage P1_Arsenal_Enter3;
    public static BufferedImage P1_Arsenal_P2_Arsenal;
    public static BufferedImage P1_Arsenal_P2_Arsenal_Chelsea;
    public static BufferedImage P1_Arsenal_P2_Arsenal_Chelsea_Reverse;
    public static BufferedImage P1_Arsenal_P2_Arsenal_Enter;
    public static BufferedImage P1_Arsenal_P2_Chelsea;
    public static BufferedImage P1_Arsenal_P2_Chelsea_Enter;
    public static BufferedImage P1_Arsenal_P2_Chelsea_Enter2;
    public static BufferedImage P1_Arsenal_P2_Chelsea_Enter3;
    public static BufferedImage P1_Arsenal_P2_Chelsea_Enter4;
    public static BufferedImage P1_Arsenal_P2_Chelsea_Enter5;
    public static BufferedImage P1_Arsenal_P2_Chelsea_Enter6;
    public static BufferedImage P1_Arsenal_P2_Chelsea_Liverpool;
    public static BufferedImage P1_Arsenal_P2_Chelsea_Liverpool_Reverse;
    public static BufferedImage P1_Arsenal_P2_Liverpool;
    public static BufferedImage P1_Arsenal_P2_Liverpool_Enter;
    public static BufferedImage P1_Arsenal_P2_Liverpool_Enter2;
    public static BufferedImage P1_Arsenal_P2_Liverpool_Enter3;
    public static BufferedImage P1_Arsenal_P2_Liverpool_Enter4;
    public static BufferedImage P1_Arsenal_P2_Liverpool_Enter5;
    public static BufferedImage P1_Arsenal_P2_Liverpool_Enter6;
    public static BufferedImage P1_Arsenal_P2_Liverpool_ManCity;
    public static BufferedImage P1_Arsenal_P2_Liverpool_ManCity_Reverse;
    public static BufferedImage P1_Arsenal_P2_ManCity;
    public static BufferedImage P1_Arsenal_P2_ManCity_Enter;
    public static BufferedImage P1_Arsenal_P2_ManCity_Enter2;
    public static BufferedImage P1_Arsenal_P2_ManCity_Enter3;
    public static BufferedImage P1_Arsenal_P2_ManCity_Enter4;
    public static BufferedImage P1_Arsenal_P2_ManCity_Enter5;
    public static BufferedImage P1_Arsenal_P2_ManCity_Enter6;
    public static BufferedImage P1_Chelsea;
    public static BufferedImage P1_Chelsea_Enter;
    public static BufferedImage P1_Chelsea_Enter2;
    public static BufferedImage P1_Chelsea_Enter3;
    public static BufferedImage P1_Chelsea_Liverpool;
    public static BufferedImage P1_Chelsea_Liverpool_Reverse;
    public static BufferedImage P1_Chelsea_P2_Arsenal;
    public static BufferedImage P1_Chelsea_P2_Arsenal_Chelsea;
    public static BufferedImage P1_Chelsea_P2_Arsenal_Chelsea_Reverse;
    public static BufferedImage P1_Chelsea_P2_Arsenal_Enter;
    public static BufferedImage P1_Chelsea_P2_Arsenal_Enter2;
    public static BufferedImage P1_Chelsea_P2_Arsenal_Enter3;
    public static BufferedImage P1_Chelsea_P2_Arsenal_Enter4;
    public static BufferedImage P1_Chelsea_P2_Arsenal_Enter5;
    public static BufferedImage P1_Chelsea_P2_Arsenal_Enter6;
    public static BufferedImage P1_Chelsea_P2_Chelsea;
    public static BufferedImage P1_Chelsea_P2_Chelsea_Enter;
    public static BufferedImage P1_Chelsea_P2_Chelsea_Liverpool;
    public static BufferedImage P1_Chelsea_P2_Chelsea_Liverpool_Reverse;
    public static BufferedImage P1_Chelsea_P2_Liverpool;
    public static BufferedImage P1_Chelsea_P2_Liverpool_Enter;
    public static BufferedImage P1_Chelsea_P2_Liverpool_Enter2;
    public static BufferedImage P1_Chelsea_P2_Liverpool_Enter3;
    public static BufferedImage P1_Chelsea_P2_Liverpool_Enter4;
    public static BufferedImage P1_Chelsea_P2_Liverpool_Enter5;
    public static BufferedImage P1_Chelsea_P2_Liverpool_Enter6;
    public static BufferedImage P1_Chelsea_P2_Liverpool_ManCity;
    public static BufferedImage P1_Chelsea_P2_Liverpool_ManCity_Reverse;
    public static BufferedImage P1_Chelsea_P2_ManCity;
    public static BufferedImage P1_Chelsea_P2_ManCity_Enter;
    public static BufferedImage P1_Chelsea_P2_ManCity_Enter2;
    public static BufferedImage P1_Chelsea_P2_ManCity_Enter3;
    public static BufferedImage P1_Chelsea_P2_ManCity_Enter4;
    public static BufferedImage P1_Chelsea_P2_ManCity_Enter5;
    public static BufferedImage P1_Chelsea_P2_ManCity_Enter6;
    public static BufferedImage P1_Liverpool;
    public static BufferedImage P1_Liverpool_Enter;
    public static BufferedImage P1_Liverpool_Enter2;
    public static BufferedImage P1_Liverpool_Enter3;
    public static BufferedImage P1_Liverpool_ManCity;
    public static BufferedImage P1_Liverpool_ManCity_Reverse;
    public static BufferedImage P1_Liverpool_P2_Arsenal;
    public static BufferedImage P1_Liverpool_P2_Arsenal_Chelsea;
    public static BufferedImage P1_Liverpool_P2_Arsenal_Chelsea_Reverse;
    public static BufferedImage P1_Liverpool_P2_Arsenal_Enter;
    public static BufferedImage P1_Liverpool_P2_Arsenal_Enter2;
    public static BufferedImage P1_Liverpool_P2_Arsenal_Enter3;
    public static BufferedImage P1_Liverpool_P2_Arsenal_Enter4;
    public static BufferedImage P1_Liverpool_P2_Arsenal_Enter5;
    public static BufferedImage P1_Liverpool_P2_Arsenal_Enter6;
    public static BufferedImage P1_Liverpool_P2_Chelsea;
    public static BufferedImage P1_Liverpool_P2_Chelsea_Enter;
    public static BufferedImage P1_Liverpool_P2_Chelsea_Enter2;
    public static BufferedImage P1_Liverpool_P2_Chelsea_Enter3;
    public static BufferedImage P1_Liverpool_P2_Chelsea_Enter4;
    public static BufferedImage P1_Liverpool_P2_Chelsea_Enter5;
    public static BufferedImage P1_Liverpool_P2_Chelsea_Enter6;
    public static BufferedImage P1_Liverpool_P2_Chelsea_Liverpool;
    public static BufferedImage P1_Liverpool_P2_Chelsea_Liverpool_Reverse;
    public static BufferedImage P1_Liverpool_P2_Liverpool;
    public static BufferedImage P1_Liverpool_P2_Liverpool_Enter;
    public static BufferedImage P1_Liverpool_P2_Liverpool_ManCity;
    public static BufferedImage P1_Liverpool_P2_Liverpool_ManCity_Reverse;
    public static BufferedImage P1_Liverpool_P2_ManCity;
    public static BufferedImage P1_Liverpool_P2_ManCity_Enter;
    public static BufferedImage P1_Liverpool_P2_ManCity_Enter2;
    public static BufferedImage P1_Liverpool_P2_ManCity_Enter3;
    public static BufferedImage P1_Liverpool_P2_ManCity_Enter4;
    public static BufferedImage P1_Liverpool_P2_ManCity_Enter5;
    public static BufferedImage P1_Liverpool_P2_ManCity_Enter6;
    public static BufferedImage P1_ManCity;
    public static BufferedImage P1_ManCity_Enter;
    public static BufferedImage P1_ManCity_Enter2;
    public static BufferedImage P1_ManCity_Enter3;
    public static BufferedImage P1_ManCity_P2_Arsenal;
    public static BufferedImage P1_ManCity_P2_Arsenal_Chelsea;
    public static BufferedImage P1_ManCity_P2_Arsenal_Chelsea_Reverse;
    public static BufferedImage P1_ManCity_P2_Arsenal_Enter;
    public static BufferedImage P1_ManCity_P2_Arsenal_Enter2;
    public static BufferedImage P1_ManCity_P2_Arsenal_Enter3;
    public static BufferedImage P1_ManCity_P2_Arsenal_Enter4;
    public static BufferedImage P1_ManCity_P2_Arsenal_Enter5;
    public static BufferedImage P1_ManCity_P2_Arsenal_Enter6;
    public static BufferedImage P1_ManCity_P2_Chelsea;
    public static BufferedImage P1_ManCity_P2_Chelsea_Enter;
    public static BufferedImage P1_ManCity_P2_Chelsea_Enter2;
    public static BufferedImage P1_ManCity_P2_Chelsea_Enter3;
    public static BufferedImage P1_ManCity_P2_Chelsea_Enter4;
    public static BufferedImage P1_ManCity_P2_Chelsea_Enter5;
    public static BufferedImage P1_ManCity_P2_Chelsea_Enter6;
    public static BufferedImage P1_ManCity_P2_Chelsea_Liverpool;
    public static BufferedImage P1_ManCity_P2_Chelsea_Liverpool_Reverse;
    public static BufferedImage P1_ManCity_P2_Liverpool;
    public static BufferedImage P1_ManCity_P2_Liverpool_Enter;
    public static BufferedImage P1_ManCity_P2_Liverpool_Enter2;
    public static BufferedImage P1_ManCity_P2_Liverpool_Enter3;
    public static BufferedImage P1_ManCity_P2_Liverpool_Enter4;
    public static BufferedImage P1_ManCity_P2_Liverpool_Enter5;
    public static BufferedImage P1_ManCity_P2_Liverpool_Enter6;
    public static BufferedImage P1_ManCity_P2_Liverpool_ManCity;
    public static BufferedImage P1_ManCity_P2_Liverpool_ManCity_Reverse;
    public static BufferedImage P1_ManCity_P2_ManCity;
    public static BufferedImage P1_ManCity_P2_ManCity_Enter;


    public static BufferedImage arsenalRunningWithoutBallE1;
    public static BufferedImage arsenalRunningWithoutBallE2;
    public static BufferedImage arsenalRunningWithoutBallE3;
    public static BufferedImage arsenalRunningWithoutBallE4;
    public static BufferedImage arsenalRunningWithoutBallW1;
    public static BufferedImage arsenalRunningWithoutBallW2;
    public static BufferedImage arsenalRunningWithoutBallW3;
    public static BufferedImage arsenalRunningWithoutBallW4;
    public static BufferedImage arsenalRunningWithoutBallN1;
    public static BufferedImage arsenalRunningWithoutBallN2;
    public static BufferedImage arsenalRunningWithoutBallN3;
    public static BufferedImage arsenalRunningWithoutBallN4;
    public static BufferedImage arsenalRunningWithoutBallS1;
    public static BufferedImage arsenalRunningWithoutBallS2;
    public static BufferedImage arsenalRunningWithoutBallS3;
    public static BufferedImage arsenalRunningWithoutBallS4;
    public static BufferedImage arsenalRunningWithoutBallNE1;
    public static BufferedImage arsenalRunningWithoutBallNE2;
    public static BufferedImage arsenalRunningWithoutBallNE3;
    public static BufferedImage arsenalRunningWithoutBallNE4;
    public static BufferedImage arsenalRunningWithoutBallNW1;
    public static BufferedImage arsenalRunningWithoutBallNW2;
    public static BufferedImage arsenalRunningWithoutBallNW3;
    public static BufferedImage arsenalRunningWithoutBallNW4;
    public static BufferedImage arsenalRunningWithoutBallSE1;
    public static BufferedImage arsenalRunningWithoutBallSE2;
    public static BufferedImage arsenalRunningWithoutBallSE3;
    public static BufferedImage arsenalRunningWithoutBallSE4;
    public static BufferedImage arsenalRunningWithoutBallSW1;
    public static BufferedImage arsenalRunningWithoutBallSW2;
    public static BufferedImage arsenalRunningWithoutBallSW3;
    public static BufferedImage arsenalRunningWithoutBallSW4;

    public static BufferedImage arsenalRunningWithBallE1;
    public static BufferedImage arsenalRunningWithBallE2;
    public static BufferedImage arsenalRunningWithBallE3;
    public static BufferedImage arsenalRunningWithBallE4;
    public static BufferedImage arsenalRunningWithBallW1;
    public static BufferedImage arsenalRunningWithBallW2;
    public static BufferedImage arsenalRunningWithBallW3;
    public static BufferedImage arsenalRunningWithBallW4;
    public static BufferedImage arsenalRunningWithBallN1;
    public static BufferedImage arsenalRunningWithBallN2;
    public static BufferedImage arsenalRunningWithBallN3;
    public static BufferedImage arsenalRunningWithBallN4;
    public static BufferedImage arsenalRunningWithBallS1;
    public static BufferedImage arsenalRunningWithBallS2;
    public static BufferedImage arsenalRunningWithBallS3;
    public static BufferedImage arsenalRunningWithBallS4;
    public static BufferedImage arsenalRunningWithBallNE1;
    public static BufferedImage arsenalRunningWithBallNE2;
    public static BufferedImage arsenalRunningWithBallNE3;
    public static BufferedImage arsenalRunningWithBallNE4;
    public static BufferedImage arsenalRunningWithBallNW1;
    public static BufferedImage arsenalRunningWithBallNW2;
    public static BufferedImage arsenalRunningWithBallNW3;
    public static BufferedImage arsenalRunningWithBallNW4;
    public static BufferedImage arsenalRunningWithBallSE1;
    public static BufferedImage arsenalRunningWithBallSE2;
    public static BufferedImage arsenalRunningWithBallSE3;
    public static BufferedImage arsenalRunningWithBallSE4;
    public static BufferedImage arsenalRunningWithBallSW1;
    public static BufferedImage arsenalRunningWithBallSW2;
    public static BufferedImage arsenalRunningWithBallSW3;
    public static BufferedImage arsenalRunningWithBallSW4;

    public static BufferedImage chelseaRunningWithoutBallE1;
    public static BufferedImage chelseaRunningWithoutBallE2;
    public static BufferedImage chelseaRunningWithoutBallE3;
    public static BufferedImage chelseaRunningWithoutBallE4;
    public static BufferedImage chelseaRunningWithoutBallW1;
    public static BufferedImage chelseaRunningWithoutBallW2;
    public static BufferedImage chelseaRunningWithoutBallW3;
    public static BufferedImage chelseaRunningWithoutBallW4;
    public static BufferedImage chelseaRunningWithoutBallN1;
    public static BufferedImage chelseaRunningWithoutBallN2;
    public static BufferedImage chelseaRunningWithoutBallN3;
    public static BufferedImage chelseaRunningWithoutBallN4;
    public static BufferedImage chelseaRunningWithoutBallS1;
    public static BufferedImage chelseaRunningWithoutBallS2;
    public static BufferedImage chelseaRunningWithoutBallS3;
    public static BufferedImage chelseaRunningWithoutBallS4;
    public static BufferedImage chelseaRunningWithoutBallNE1;
    public static BufferedImage chelseaRunningWithoutBallNE2;
    public static BufferedImage chelseaRunningWithoutBallNE3;
    public static BufferedImage chelseaRunningWithoutBallNE4;
    public static BufferedImage chelseaRunningWithoutBallNW1;
    public static BufferedImage chelseaRunningWithoutBallNW2;
    public static BufferedImage chelseaRunningWithoutBallNW3;
    public static BufferedImage chelseaRunningWithoutBallNW4;
    public static BufferedImage chelseaRunningWithoutBallSE1;
    public static BufferedImage chelseaRunningWithoutBallSE2;
    public static BufferedImage chelseaRunningWithoutBallSE3;
    public static BufferedImage chelseaRunningWithoutBallSE4;
    public static BufferedImage chelseaRunningWithoutBallSW1;
    public static BufferedImage chelseaRunningWithoutBallSW2;
    public static BufferedImage chelseaRunningWithoutBallSW3;
    public static BufferedImage chelseaRunningWithoutBallSW4;

    public static BufferedImage chelseaRunningWithBallE1;
    public static BufferedImage chelseaRunningWithBallE2;
    public static BufferedImage chelseaRunningWithBallE3;
    public static BufferedImage chelseaRunningWithBallE4;
    public static BufferedImage chelseaRunningWithBallW1;
    public static BufferedImage chelseaRunningWithBallW2;
    public static BufferedImage chelseaRunningWithBallW3;
    public static BufferedImage chelseaRunningWithBallW4;
    public static BufferedImage chelseaRunningWithBallN1;
    public static BufferedImage chelseaRunningWithBallN2;
    public static BufferedImage chelseaRunningWithBallN3;
    public static BufferedImage chelseaRunningWithBallN4;
    public static BufferedImage chelseaRunningWithBallS1;
    public static BufferedImage chelseaRunningWithBallS2;
    public static BufferedImage chelseaRunningWithBallS3;
    public static BufferedImage chelseaRunningWithBallS4;
    public static BufferedImage chelseaRunningWithBallNE1;
    public static BufferedImage chelseaRunningWithBallNE2;
    public static BufferedImage chelseaRunningWithBallNE3;
    public static BufferedImage chelseaRunningWithBallNE4;
    public static BufferedImage chelseaRunningWithBallNW1;
    public static BufferedImage chelseaRunningWithBallNW2;
    public static BufferedImage chelseaRunningWithBallNW3;
    public static BufferedImage chelseaRunningWithBallNW4;
    public static BufferedImage chelseaRunningWithBallSE1;
    public static BufferedImage chelseaRunningWithBallSE2;
    public static BufferedImage chelseaRunningWithBallSE3;
    public static BufferedImage chelseaRunningWithBallSE4;
    public static BufferedImage chelseaRunningWithBallSW1;
    public static BufferedImage chelseaRunningWithBallSW2;
    public static BufferedImage chelseaRunningWithBallSW3;
    public static BufferedImage chelseaRunningWithBallSW4;

    public static BufferedImage manCityRunningWithoutBallE1;
    public static BufferedImage manCityRunningWithoutBallE2;
    public static BufferedImage manCityRunningWithoutBallE3;
    public static BufferedImage manCityRunningWithoutBallE4;
    public static BufferedImage manCityRunningWithoutBallW1;
    public static BufferedImage manCityRunningWithoutBallW2;
    public static BufferedImage manCityRunningWithoutBallW3;
    public static BufferedImage manCityRunningWithoutBallW4;
    public static BufferedImage manCityRunningWithoutBallN1;
    public static BufferedImage manCityRunningWithoutBallN2;
    public static BufferedImage manCityRunningWithoutBallN3;
    public static BufferedImage manCityRunningWithoutBallN4;
    public static BufferedImage manCityRunningWithoutBallS1;
    public static BufferedImage manCityRunningWithoutBallS2;
    public static BufferedImage manCityRunningWithoutBallS3;
    public static BufferedImage manCityRunningWithoutBallS4;
    public static BufferedImage manCityRunningWithoutBallNE1;
    public static BufferedImage manCityRunningWithoutBallNE2;
    public static BufferedImage manCityRunningWithoutBallNE3;
    public static BufferedImage manCityRunningWithoutBallNE4;
    public static BufferedImage manCityRunningWithoutBallNW1;
    public static BufferedImage manCityRunningWithoutBallNW2;
    public static BufferedImage manCityRunningWithoutBallNW3;
    public static BufferedImage manCityRunningWithoutBallNW4;
    public static BufferedImage manCityRunningWithoutBallSE1;
    public static BufferedImage manCityRunningWithoutBallSE2;
    public static BufferedImage manCityRunningWithoutBallSE3;
    public static BufferedImage manCityRunningWithoutBallSE4;
    public static BufferedImage manCityRunningWithoutBallSW1;
    public static BufferedImage manCityRunningWithoutBallSW2;
    public static BufferedImage manCityRunningWithoutBallSW3;
    public static BufferedImage manCityRunningWithoutBallSW4;

    public static BufferedImage manCityRunningWithBallE1;
    public static BufferedImage manCityRunningWithBallE2;
    public static BufferedImage manCityRunningWithBallE3;
    public static BufferedImage manCityRunningWithBallE4;
    public static BufferedImage manCityRunningWithBallW1;
    public static BufferedImage manCityRunningWithBallW2;
    public static BufferedImage manCityRunningWithBallW3;
    public static BufferedImage manCityRunningWithBallW4;
    public static BufferedImage manCityRunningWithBallN1;
    public static BufferedImage manCityRunningWithBallN2;
    public static BufferedImage manCityRunningWithBallN3;
    public static BufferedImage manCityRunningWithBallN4;
    public static BufferedImage manCityRunningWithBallS1;
    public static BufferedImage manCityRunningWithBallS2;
    public static BufferedImage manCityRunningWithBallS3;
    public static BufferedImage manCityRunningWithBallS4;
    public static BufferedImage manCityRunningWithBallNE1;
    public static BufferedImage manCityRunningWithBallNE2;
    public static BufferedImage manCityRunningWithBallNE3;
    public static BufferedImage manCityRunningWithBallNE4;
    public static BufferedImage manCityRunningWithBallNW1;
    public static BufferedImage manCityRunningWithBallNW2;
    public static BufferedImage manCityRunningWithBallNW3;
    public static BufferedImage manCityRunningWithBallNW4;
    public static BufferedImage manCityRunningWithBallSE1;
    public static BufferedImage manCityRunningWithBallSE2;
    public static BufferedImage manCityRunningWithBallSE3;
    public static BufferedImage manCityRunningWithBallSE4;
    public static BufferedImage manCityRunningWithBallSW1;
    public static BufferedImage manCityRunningWithBallSW2;
    public static BufferedImage manCityRunningWithBallSW3;
    public static BufferedImage manCityRunningWithBallSW4;

    public static BufferedImage liverpoolRunningWithoutBallE1;
    public static BufferedImage liverpoolRunningWithoutBallE2;
    public static BufferedImage liverpoolRunningWithoutBallE3;
    public static BufferedImage liverpoolRunningWithoutBallE4;
    public static BufferedImage liverpoolRunningWithoutBallW1;
    public static BufferedImage liverpoolRunningWithoutBallW2;
    public static BufferedImage liverpoolRunningWithoutBallW3;
    public static BufferedImage liverpoolRunningWithoutBallW4;
    public static BufferedImage liverpoolRunningWithoutBallN1;
    public static BufferedImage liverpoolRunningWithoutBallN2;
    public static BufferedImage liverpoolRunningWithoutBallN3;
    public static BufferedImage liverpoolRunningWithoutBallN4;
    public static BufferedImage liverpoolRunningWithoutBallS1;
    public static BufferedImage liverpoolRunningWithoutBallS2;
    public static BufferedImage liverpoolRunningWithoutBallS3;
    public static BufferedImage liverpoolRunningWithoutBallS4;
    public static BufferedImage liverpoolRunningWithoutBallNE1;
    public static BufferedImage liverpoolRunningWithoutBallNE2;
    public static BufferedImage liverpoolRunningWithoutBallNE3;
    public static BufferedImage liverpoolRunningWithoutBallNE4;
    public static BufferedImage liverpoolRunningWithoutBallNW1;
    public static BufferedImage liverpoolRunningWithoutBallNW2;
    public static BufferedImage liverpoolRunningWithoutBallNW3;
    public static BufferedImage liverpoolRunningWithoutBallNW4;
    public static BufferedImage liverpoolRunningWithoutBallSE1;
    public static BufferedImage liverpoolRunningWithoutBallSE2;
    public static BufferedImage liverpoolRunningWithoutBallSE3;
    public static BufferedImage liverpoolRunningWithoutBallSE4;
    public static BufferedImage liverpoolRunningWithoutBallSW1;
    public static BufferedImage liverpoolRunningWithoutBallSW2;
    public static BufferedImage liverpoolRunningWithoutBallSW3;
    public static BufferedImage liverpoolRunningWithoutBallSW4;

    public static BufferedImage liverpoolRunningWithBallE1;
    public static BufferedImage liverpoolRunningWithBallE2;
    public static BufferedImage liverpoolRunningWithBallE3;
    public static BufferedImage liverpoolRunningWithBallE4;
    public static BufferedImage liverpoolRunningWithBallW1;
    public static BufferedImage liverpoolRunningWithBallW2;
    public static BufferedImage liverpoolRunningWithBallW3;
    public static BufferedImage liverpoolRunningWithBallW4;
    public static BufferedImage liverpoolRunningWithBallN1;
    public static BufferedImage liverpoolRunningWithBallN2;
    public static BufferedImage liverpoolRunningWithBallN3;
    public static BufferedImage liverpoolRunningWithBallN4;
    public static BufferedImage liverpoolRunningWithBallS1;
    public static BufferedImage liverpoolRunningWithBallS2;
    public static BufferedImage liverpoolRunningWithBallS3;
    public static BufferedImage liverpoolRunningWithBallS4;
    public static BufferedImage liverpoolRunningWithBallNE1;
    public static BufferedImage liverpoolRunningWithBallNE2;
    public static BufferedImage liverpoolRunningWithBallNE3;
    public static BufferedImage liverpoolRunningWithBallNE4;
    public static BufferedImage liverpoolRunningWithBallNW1;
    public static BufferedImage liverpoolRunningWithBallNW2;
    public static BufferedImage liverpoolRunningWithBallNW3;
    public static BufferedImage liverpoolRunningWithBallNW4;
    public static BufferedImage liverpoolRunningWithBallSE1;
    public static BufferedImage liverpoolRunningWithBallSE2;
    public static BufferedImage liverpoolRunningWithBallSE3;
    public static BufferedImage liverpoolRunningWithBallSE4;
    public static BufferedImage liverpoolRunningWithBallSW1;
    public static BufferedImage liverpoolRunningWithBallSW2;
    public static BufferedImage liverpoolRunningWithBallSW3;
    public static BufferedImage liverpoolRunningWithBallSW4;


    public static BufferedImage arsenalPassE;
    public static BufferedImage arsenalPassW;
    public static BufferedImage arsenalPassN;
    public static BufferedImage arsenalPassS;
    public static BufferedImage arsenalPassNE;
    public static BufferedImage arsenalPassSE;
    public static BufferedImage arsenalPassNW;
    public static BufferedImage arsenalPassSW;
    public static BufferedImage chelseaPassE;
    public static BufferedImage chelseaPassW;
    public static BufferedImage chelseaPassN;
    public static BufferedImage chelseaPassS;
    public static BufferedImage chelseaPassNE;
    public static BufferedImage chelseaPassSE;
    public static BufferedImage chelseaPassNW;
    public static BufferedImage chelseaPassSW;
    public static BufferedImage manCityPassE;
    public static BufferedImage manCityPassW;
    public static BufferedImage manCityPassN;
    public static BufferedImage manCityPassS;
    public static BufferedImage manCityPassNE;
    public static BufferedImage manCityPassSE;
    public static BufferedImage manCityPassNW;
    public static BufferedImage manCityPassSW;
    public static BufferedImage liverpoolPassE;
    public static BufferedImage liverpoolPassW;
    public static BufferedImage liverpoolPassN;
    public static BufferedImage liverpoolPassS;
    public static BufferedImage liverpoolPassNE;
    public static BufferedImage liverpoolPassSE;
    public static BufferedImage liverpoolPassNW;
    public static BufferedImage liverpoolPassSW;

    public static BufferedImage arsenaltackleNE;
    public static BufferedImage arsenaltackleSE;
    public static BufferedImage arsenaltackleNW;
    public static BufferedImage arsenaltackleSW;
    public static BufferedImage chelseatackleNE;
    public static BufferedImage chelseatackleSE;
    public static BufferedImage chelseatackleNW;
    public static BufferedImage chelseatackleSW;
    public static BufferedImage manCitytackleNE;
    public static BufferedImage manCitytackleSE;
    public static BufferedImage manCitytackleNW;
    public static BufferedImage manCitytackleSW;
    public static BufferedImage liverpooltackleNE;
    public static BufferedImage liverpooltackleSE;
    public static BufferedImage liverpooltackleNW;
    public static BufferedImage liverpooltackleSW;

    public static BufferedImage arsenalWait1;
    public static BufferedImage arsenalWait2;
    public static BufferedImage chelseaWait1;
    public static BufferedImage chelseaWait2;
    public static BufferedImage manCityWait1;
    public static BufferedImage manCityWait2;
    public static BufferedImage liverpoolWait1;
    public static BufferedImage liverpoolWait2;


    public static BufferedImage heroLeft4;
    public static BufferedImage heroLeft41;
    public static BufferedImage heroLeft42;
    public static BufferedImage heroLeft43;

    public static BufferedImage heroRight4;
    public static BufferedImage heroRight41;
    public static BufferedImage heroRight42;
    public static BufferedImage heroRight43;

    public static BufferedImage block4;


    public static BufferedImage staff1;
    public static BufferedImage staff2;
    public static BufferedImage staff3;
    public static BufferedImage staff4;
    public static BufferedImage staff5;
    public static BufferedImage staff6;
    public static BufferedImage staff7;
    public static BufferedImage staff8;
    public static BufferedImage staff9;
    public static BufferedImage staff10;
    public static BufferedImage staff11;
    public static BufferedImage staff12;
    public static BufferedImage staff13;
    public static BufferedImage staff14;
    public static BufferedImage staff15;
    public static BufferedImage staff16;
    public static BufferedImage staff17;
    public static BufferedImage staff18;
    public static BufferedImage staff19;
    public static BufferedImage staff20;
    public static BufferedImage staff21;
    public static BufferedImage staff22;
    public static BufferedImage staff23;
    public static BufferedImage staff24;
    public static BufferedImage staff25;
    public static BufferedImage staff26;
    public static BufferedImage staff27;
    public static BufferedImage staff28;
    public static BufferedImage staff29;
    public static BufferedImage staff30;
    public static BufferedImage staff31;
    public static BufferedImage staff32;
    public static BufferedImage staff33;
    public static BufferedImage staff34;
    public static BufferedImage staff35;
    public static BufferedImage staff36;
    public static BufferedImage staff37;
    public static BufferedImage staff38;
    public static BufferedImage staff39;
    public static BufferedImage staff40;
    public static BufferedImage staff41;
    public static BufferedImage staff42;
    public static BufferedImage staff43;
    public static BufferedImage staff44;
    public static BufferedImage staff45;
    public static BufferedImage staff46;
    public static BufferedImage staff47;
    public static BufferedImage staff48;
    public static BufferedImage staff49;

    public static BufferedImage lights;

    public static BufferedImage tribune_Red;
    public static BufferedImage tribune_Blue;
    public static BufferedImage tribune_Arsenal1;
    public static BufferedImage tribune_Arsenal2;
    public static BufferedImage tribune_Arsenal3;
    public static BufferedImage tribune_Arsenal4;
    public static BufferedImage tribune_Arsenal5;
    public static BufferedImage tribune_Arsenal6;
    public static BufferedImage tribune_Chelsea1;
    public static BufferedImage tribune_Chelsea2;
    public static BufferedImage tribune_Chelsea3;
    public static BufferedImage tribune_Chelsea4;
    public static BufferedImage tribune_Chelsea5;
    public static BufferedImage tribune_Chelsea6;
    public static BufferedImage tribune_Liverpool1;
    public static BufferedImage tribune_Liverpool2;
    public static BufferedImage tribune_Liverpool3;
    public static BufferedImage tribune_Liverpool4;
    public static BufferedImage tribune_Liverpool5;
    public static BufferedImage tribune_Liverpool6;
    public static BufferedImage tribune_ManCity1;
    public static BufferedImage tribune_ManCity2;
    public static BufferedImage tribune_ManCity3;
    public static BufferedImage tribune_ManCity4;
    public static BufferedImage tribune_ManCity5;
    public static BufferedImage tribune_ManCity6;

    public static BufferedImage ball1;
    public static BufferedImage ball2;
    public static BufferedImage ball3;
    public static BufferedImage ball4;
    public static BufferedImage ball5;
    public static BufferedImage ball6;
    public static BufferedImage ball7;
    public static BufferedImage ball8;
    public static BufferedImage ball9;


    /*! \fn public static void Init()
        \brief Functia initializaza referintele catre elementele grafice utilizate.

        Aceasta functie poate fi rescrisa astfel incat elementele grafice incarcate/utilizate
        sa fie parametrizate. Din acest motiv referintele nu sunt finale.
     */
    public static void Init()
    {
            /// Se creaza temporar un obiect SpriteSheet initializat prin intermediul clasei ImageLoader
        SpriteSheet ball = new SpriteSheet(ImageLoader.LoadImage("/textures/ball.png"));
        SpriteSheet fotbal = new SpriteSheet(ImageLoader.LoadImage("/textures/Football.png"));
        SpriteSheet utilities = new SpriteSheet(ImageLoader.LoadImage("/textures/Utilities.png"));
        SpriteSheet arsenalMoves1 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ArsenalRunningWithBall.png"));
        SpriteSheet arsenalMoves2 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ArsenalRunningWithBall2.png"));
        SpriteSheet arsenalMoves3 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ArsenalRunningWithoutBall.png"));
        SpriteSheet arsenalMoves4 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ArsenalRunningWithoutBall2.png"));
        SpriteSheet arsenalSpecialMoves = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ArsenalActions.png"));
        SpriteSheet manCityMoves1 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ManCityRunningWithBall.png"));
        SpriteSheet manCityMoves2 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ManCityRunningWithBall2.png"));
        SpriteSheet manCityMoves3 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ManCityRunningWithoutBall.png"));
        SpriteSheet manCityMoves4 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ManCityRunningWithoutBall2.png"));
        SpriteSheet manCitySpecialMoves = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ManCityActions.png"));
        SpriteSheet chelseaMoves1 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ChelseaRunningWithBall.png"));
        SpriteSheet chelseaMoves2 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ChelseaRunningWithBall2.png"));
        SpriteSheet chelseaMoves3 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ChelseaRunningWithoutBall.png"));
        SpriteSheet chelseaMoves4 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ChelseaRunningWithoutBall2.png"));
        SpriteSheet chelseaSpecialMoves = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/ChelseaActions.png"));
        SpriteSheet liverpoolMoves1 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/LiverpoolRunningWithBall.png"));
        SpriteSheet liverpoolMoves2 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/LiverpoolRunningWithBall2.png"));
        SpriteSheet liverpoolMoves3 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/LiverpoolRunningWithoutBall.png"));
        SpriteSheet liverpoolMoves4 = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/LiverpoolRunningWithoutBall2.png"));
        SpriteSheet liverpoolSpecialMoves = new SpriteSheet(ImageLoader.LoadImage("/textures/Players/LiverpoolActions.png"));


        goalNetLeft = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft.png");
        goalNetLeft1 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft1.png");
        goalNetLeft2 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft2.png");
        goalNetLeft3 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft3.png");
        goalNetLeft4 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft4.png");
        goalNetLeft5 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft5.png");
        goalNetLeft6 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft6.png");
        goalNetLeft7 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft7.png");
        goalNetLeft8 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft8.png");
        goalNetLeft9 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft9.png");
        goalNetLeft10 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft10.png");
        goalNetLeft21 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft21.png");
        goalNetLeft22 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft22.png");
        goalNetLeft23 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft23.png");
        goalNetLeft24 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft24.png");
        goalNetLeft25 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft25.png");
        goalNetLeft26 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft26.png");
        goalNetLeft27 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft27.png");
        goalNetLeft28 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetLeft28.png");

        goalNetRight = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight.png");
        goalNetRight1 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight1.png");
        goalNetRight2 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight2.png");
        goalNetRight3 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight3.png");
        goalNetRight4 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight4.png");
        goalNetRight5 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight5.png");
        goalNetRight6 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight6.png");
        goalNetRight7 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight7.png");
        goalNetRight8 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight8.png");
        goalNetRight9 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight9.png");
        goalNetRight10 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight10.png");
        goalNetRight21 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight3.png");
        goalNetRight22 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight22.png");
        goalNetRight23 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight23.png");
        goalNetRight24 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight24.png");
        goalNetRight25 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight25.png");
        goalNetRight26 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight26.png");
        goalNetRight27 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight27.png");
        goalNetRight28 = ImageLoader.LoadImage("/textures/GoalPost/GoalNetRight28.png");

        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /// Se obtin subimaginile corespunzatoare elementelor necesare.
        arsenalRunningWithBallW1 = arsenalMoves1.crop(0,0);
        arsenalRunningWithBallW2 = arsenalMoves1.crop(0,3);
        arsenalRunningWithBallW3 = arsenalMoves1.crop(0,2);
        arsenalRunningWithBallW4 = arsenalMoves1.crop(0,1);
        arsenalRunningWithBallE1 = arsenalMoves1.crop(1,3);
        arsenalRunningWithBallE2 = arsenalMoves1.crop(1,0);
        arsenalRunningWithBallE3 = arsenalMoves1.crop(1,1);
        arsenalRunningWithBallE4 = arsenalMoves1.crop(1,2);
        arsenalRunningWithBallN1 = arsenalMoves2.crop(2,0);
        arsenalRunningWithBallN2 = arsenalMoves2.crop(2,1);
        arsenalRunningWithBallN3 = arsenalMoves2.crop(2,2);
        arsenalRunningWithBallN4 = arsenalMoves2.crop(2,3);
        arsenalRunningWithBallS1 = arsenalMoves2.crop(3,0);
        arsenalRunningWithBallS2 = arsenalMoves2.crop(3,1);
        arsenalRunningWithBallS3 = arsenalMoves2.crop(3,2);
        arsenalRunningWithBallS4 = arsenalMoves2.crop(3,3);
        arsenalRunningWithBallNE1 = arsenalMoves2.crop(1,3);
        arsenalRunningWithBallNE2 = arsenalMoves2.crop(1,0);
        arsenalRunningWithBallNE3 = arsenalMoves2.crop(1,1);
        arsenalRunningWithBallNE4 = arsenalMoves2.crop(1,2);
        arsenalRunningWithBallSE1 = arsenalMoves1.crop(3,3);
        arsenalRunningWithBallSE2 = arsenalMoves1.crop(3,0);
        arsenalRunningWithBallSE3 = arsenalMoves1.crop(3,1);
        arsenalRunningWithBallSE4 = arsenalMoves1.crop(3,2);
        arsenalRunningWithBallNW1 = arsenalMoves2.crop(0,0);
        arsenalRunningWithBallNW2 = arsenalMoves2.crop(0,1);
        arsenalRunningWithBallNW3 = arsenalMoves2.crop(0,2);
        arsenalRunningWithBallNW4 = arsenalMoves2.crop(0,3);
        arsenalRunningWithBallSW1 = arsenalMoves1.crop(2,0);
        arsenalRunningWithBallSW2 = arsenalMoves1.crop(2,1);
        arsenalRunningWithBallSW3 = arsenalMoves1.crop(2,2);
        arsenalRunningWithBallSW4 = arsenalMoves1.crop(2,3);

        arsenalRunningWithoutBallW1 = arsenalMoves3.crop(0,0);
        arsenalRunningWithoutBallW2 = arsenalMoves3.crop(0,3);
        arsenalRunningWithoutBallW3 = arsenalMoves3.crop(0,2);
        arsenalRunningWithoutBallW4 = arsenalMoves3.crop(0,1);
        arsenalRunningWithoutBallE1 = arsenalMoves3.crop(1,3);
        arsenalRunningWithoutBallE2 = arsenalMoves3.crop(1,0);
        arsenalRunningWithoutBallE3 = arsenalMoves3.crop(1,1);
        arsenalRunningWithoutBallE4 = arsenalMoves3.crop(1,2);
        arsenalRunningWithoutBallN1 = arsenalMoves4.crop(2,0);
        arsenalRunningWithoutBallN2 = arsenalMoves4.crop(2,1);
        arsenalRunningWithoutBallN3 = arsenalMoves4.crop(2,2);
        arsenalRunningWithoutBallN4 = arsenalMoves4.crop(2,3);
        arsenalRunningWithoutBallS1 = arsenalMoves4.crop(3,0);
        arsenalRunningWithoutBallS2 = arsenalMoves4.crop(3,1);
        arsenalRunningWithoutBallS3 = arsenalMoves4.crop(3,2);
        arsenalRunningWithoutBallS4 = arsenalMoves4.crop(3,3);
        arsenalRunningWithoutBallNE1 = arsenalMoves4.crop(1,3);
        arsenalRunningWithoutBallNE2 = arsenalMoves4.crop(1,0);
        arsenalRunningWithoutBallNE3 = arsenalMoves4.crop(1,1);
        arsenalRunningWithoutBallNE4 = arsenalMoves4.crop(1,2);
        arsenalRunningWithoutBallSE1 = arsenalMoves3.crop(3,3);
        arsenalRunningWithoutBallSE2 = arsenalMoves3.crop(3,0);
        arsenalRunningWithoutBallSE3 = arsenalMoves3.crop(3,1);
        arsenalRunningWithoutBallSE4 = arsenalMoves3.crop(3,2);
        arsenalRunningWithoutBallNW1 = arsenalMoves4.crop(0,0);
        arsenalRunningWithoutBallNW2 = arsenalMoves4.crop(0,1);
        arsenalRunningWithoutBallNW3 = arsenalMoves4.crop(0,2);
        arsenalRunningWithoutBallNW4 = arsenalMoves4.crop(0,3);
        arsenalRunningWithoutBallSW1 = arsenalMoves3.crop(2,0);
        arsenalRunningWithoutBallSW2 = arsenalMoves3.crop(2,1);
        arsenalRunningWithoutBallSW3 = arsenalMoves3.crop(2,2);
        arsenalRunningWithoutBallSW4 = arsenalMoves3.crop(2,3);

        chelseaRunningWithBallW1 = chelseaMoves1.crop(0,0);
        chelseaRunningWithBallW2 = chelseaMoves1.crop(0,3);
        chelseaRunningWithBallW3 = chelseaMoves1.crop(0,2);
        chelseaRunningWithBallW4 = chelseaMoves1.crop(0,1);
        chelseaRunningWithBallE1 = chelseaMoves1.crop(1,3);
        chelseaRunningWithBallE2 = chelseaMoves1.crop(1,0);
        chelseaRunningWithBallE3 = chelseaMoves1.crop(1,1);
        chelseaRunningWithBallE4 = chelseaMoves1.crop(1,2);
        chelseaRunningWithBallN1 = chelseaMoves2.crop(2,0);
        chelseaRunningWithBallN2 = chelseaMoves2.crop(2,1);
        chelseaRunningWithBallN3 = chelseaMoves2.crop(2,2);
        chelseaRunningWithBallN4 = chelseaMoves2.crop(2,3);
        chelseaRunningWithBallS1 = chelseaMoves2.crop(3,0);
        chelseaRunningWithBallS2 = chelseaMoves2.crop(3,1);
        chelseaRunningWithBallS3 = chelseaMoves2.crop(3,2);
        chelseaRunningWithBallS4 = chelseaMoves2.crop(3,3);
        chelseaRunningWithBallNE1 = chelseaMoves2.crop(1,3);
        chelseaRunningWithBallNE2 = chelseaMoves2.crop(1,0);
        chelseaRunningWithBallNE3 = chelseaMoves2.crop(1,1);
        chelseaRunningWithBallNE4 = chelseaMoves2.crop(1,2);
        chelseaRunningWithBallSE1 = chelseaMoves1.crop(3,3);
        chelseaRunningWithBallSE2 = chelseaMoves1.crop(3,0);
        chelseaRunningWithBallSE3 = chelseaMoves1.crop(3,1);
        chelseaRunningWithBallSE4 = chelseaMoves1.crop(3,2);
        chelseaRunningWithBallNW1 = chelseaMoves2.crop(0,0);
        chelseaRunningWithBallNW2 = chelseaMoves2.crop(0,1);
        chelseaRunningWithBallNW3 = chelseaMoves2.crop(0,2);
        chelseaRunningWithBallNW4 = chelseaMoves2.crop(0,3);
        chelseaRunningWithBallSW1 = chelseaMoves1.crop(2,0);
        chelseaRunningWithBallSW2 = chelseaMoves1.crop(2,1);
        chelseaRunningWithBallSW3 = chelseaMoves1.crop(2,2);
        chelseaRunningWithBallSW4 = chelseaMoves1.crop(2,3);

        chelseaRunningWithoutBallW1 = chelseaMoves3.crop(0,0);
        chelseaRunningWithoutBallW2 = chelseaMoves3.crop(0,3);
        chelseaRunningWithoutBallW3 = chelseaMoves3.crop(0,2);
        chelseaRunningWithoutBallW4 = chelseaMoves3.crop(0,1);
        chelseaRunningWithoutBallE1 = chelseaMoves3.crop(1,3);
        chelseaRunningWithoutBallE2 = chelseaMoves3.crop(1,0);
        chelseaRunningWithoutBallE3 = chelseaMoves3.crop(1,1);
        chelseaRunningWithoutBallE4 = chelseaMoves3.crop(1,2);
        chelseaRunningWithoutBallN1 = chelseaMoves4.crop(2,0);
        chelseaRunningWithoutBallN2 = chelseaMoves4.crop(2,1);
        chelseaRunningWithoutBallN3 = chelseaMoves4.crop(2,2);
        chelseaRunningWithoutBallN4 = chelseaMoves4.crop(2,3);
        chelseaRunningWithoutBallS1 = chelseaMoves4.crop(3,0);
        chelseaRunningWithoutBallS2 = chelseaMoves4.crop(3,1);
        chelseaRunningWithoutBallS3 = chelseaMoves4.crop(3,2);
        chelseaRunningWithoutBallS4 = chelseaMoves4.crop(3,3);
        chelseaRunningWithoutBallNE1 = chelseaMoves4.crop(1,3);
        chelseaRunningWithoutBallNE2 = chelseaMoves4.crop(1,0);
        chelseaRunningWithoutBallNE3 = chelseaMoves4.crop(1,1);
        chelseaRunningWithoutBallNE4 = chelseaMoves4.crop(1,2);
        chelseaRunningWithoutBallSE1 = chelseaMoves3.crop(3,3);
        chelseaRunningWithoutBallSE2 = chelseaMoves3.crop(3,0);
        chelseaRunningWithoutBallSE3 = chelseaMoves3.crop(3,1);
        chelseaRunningWithoutBallSE4 = chelseaMoves3.crop(3,2);
        chelseaRunningWithoutBallNW1 = chelseaMoves4.crop(0,0);
        chelseaRunningWithoutBallNW2 = chelseaMoves4.crop(0,1);
        chelseaRunningWithoutBallNW3 = chelseaMoves4.crop(0,2);
        chelseaRunningWithoutBallNW4 = chelseaMoves4.crop(0,3);
        chelseaRunningWithoutBallSW1 = chelseaMoves3.crop(2,0);
        chelseaRunningWithoutBallSW2 = chelseaMoves3.crop(2,1);
        chelseaRunningWithoutBallSW3 = chelseaMoves3.crop(2,2);
        chelseaRunningWithoutBallSW4 = chelseaMoves3.crop(2,3);

        manCityRunningWithBallW1 = manCityMoves1.crop(0,0);
        manCityRunningWithBallW2 = manCityMoves1.crop(0,3);
        manCityRunningWithBallW3 = manCityMoves1.crop(0,2);
        manCityRunningWithBallW4 = manCityMoves1.crop(0,1);
        manCityRunningWithBallE1 = manCityMoves1.crop(1,3);
        manCityRunningWithBallE2 = manCityMoves1.crop(1,0);
        manCityRunningWithBallE3 = manCityMoves1.crop(1,1);
        manCityRunningWithBallE4 = manCityMoves1.crop(1,2);
        manCityRunningWithBallN1 = manCityMoves2.crop(2,0);
        manCityRunningWithBallN2 = manCityMoves2.crop(2,1);
        manCityRunningWithBallN3 = manCityMoves2.crop(2,2);
        manCityRunningWithBallN4 = manCityMoves2.crop(2,3);
        manCityRunningWithBallS1 = manCityMoves2.crop(3,0);
        manCityRunningWithBallS2 = manCityMoves2.crop(3,1);
        manCityRunningWithBallS3 = manCityMoves2.crop(3,2);
        manCityRunningWithBallS4 = manCityMoves2.crop(3,3);
        manCityRunningWithBallNE1 = manCityMoves2.crop(1,3);
        manCityRunningWithBallNE2 = manCityMoves2.crop(1,0);
        manCityRunningWithBallNE3 = manCityMoves2.crop(1,1);
        manCityRunningWithBallNE4 = manCityMoves2.crop(1,2);
        manCityRunningWithBallSE1 = manCityMoves1.crop(3,3);
        manCityRunningWithBallSE2 = manCityMoves1.crop(3,0);
        manCityRunningWithBallSE3 = manCityMoves1.crop(3,1);
        manCityRunningWithBallSE4 = manCityMoves1.crop(3,2);
        manCityRunningWithBallNW1 = manCityMoves2.crop(0,0);
        manCityRunningWithBallNW2 = manCityMoves2.crop(0,1);
        manCityRunningWithBallNW3 = manCityMoves2.crop(0,2);
        manCityRunningWithBallNW4 = manCityMoves2.crop(0,3);
        manCityRunningWithBallSW1 = manCityMoves1.crop(2,0);
        manCityRunningWithBallSW2 = manCityMoves1.crop(2,1);
        manCityRunningWithBallSW3 = manCityMoves1.crop(2,2);
        manCityRunningWithBallSW4 = manCityMoves1.crop(2,3);

        manCityRunningWithoutBallW1 = manCityMoves3.crop(0,0);
        manCityRunningWithoutBallW2 = manCityMoves3.crop(0,3);
        manCityRunningWithoutBallW3 = manCityMoves3.crop(0,2);
        manCityRunningWithoutBallW4 = manCityMoves3.crop(0,1);
        manCityRunningWithoutBallE1 = manCityMoves3.crop(1,3);
        manCityRunningWithoutBallE2 = manCityMoves3.crop(1,0);
        manCityRunningWithoutBallE3 = manCityMoves3.crop(1,1);
        manCityRunningWithoutBallE4 = manCityMoves3.crop(1,2);
        manCityRunningWithoutBallN1 = manCityMoves4.crop(2,0);
        manCityRunningWithoutBallN2 = manCityMoves4.crop(2,1);
        manCityRunningWithoutBallN3 = manCityMoves4.crop(2,2);
        manCityRunningWithoutBallN4 = manCityMoves4.crop(2,3);
        manCityRunningWithoutBallS1 = manCityMoves4.crop(3,0);
        manCityRunningWithoutBallS2 = manCityMoves4.crop(3,1);
        manCityRunningWithoutBallS3 = manCityMoves4.crop(3,2);
        manCityRunningWithoutBallS4 = manCityMoves4.crop(3,3);
        manCityRunningWithoutBallNE1 = manCityMoves4.crop(1,3);
        manCityRunningWithoutBallNE2 = manCityMoves4.crop(1,0);
        manCityRunningWithoutBallNE3 = manCityMoves4.crop(1,1);
        manCityRunningWithoutBallNE4 = manCityMoves4.crop(1,2);
        manCityRunningWithoutBallSE1 = manCityMoves3.crop(3,3);
        manCityRunningWithoutBallSE2 = manCityMoves3.crop(3,0);
        manCityRunningWithoutBallSE3 = manCityMoves3.crop(3,1);
        manCityRunningWithoutBallSE4 = manCityMoves3.crop(3,2);
        manCityRunningWithoutBallNW1 = manCityMoves4.crop(0,0);
        manCityRunningWithoutBallNW2 = manCityMoves4.crop(0,1);
        manCityRunningWithoutBallNW3 = manCityMoves4.crop(0,2);
        manCityRunningWithoutBallNW4 = manCityMoves4.crop(0,3);
        manCityRunningWithoutBallSW1 = manCityMoves3.crop(2,0);
        manCityRunningWithoutBallSW2 = manCityMoves3.crop(2,1);
        manCityRunningWithoutBallSW3 = manCityMoves3.crop(2,2);
        manCityRunningWithoutBallSW4 = manCityMoves3.crop(2,3);

        liverpoolRunningWithBallW1 = liverpoolMoves1.crop(0,0);
        liverpoolRunningWithBallW2 = liverpoolMoves1.crop(0,3);
        liverpoolRunningWithBallW3 = liverpoolMoves1.crop(0,2);
        liverpoolRunningWithBallW4 = liverpoolMoves1.crop(0,1);
        liverpoolRunningWithBallE1 = liverpoolMoves1.crop(1,3);
        liverpoolRunningWithBallE2 = liverpoolMoves1.crop(1,0);
        liverpoolRunningWithBallE3 = liverpoolMoves1.crop(1,1);
        liverpoolRunningWithBallE4 = liverpoolMoves1.crop(1,2);
        liverpoolRunningWithBallN1 = liverpoolMoves2.crop(2,0);
        liverpoolRunningWithBallN2 = liverpoolMoves2.crop(2,1);
        liverpoolRunningWithBallN3 = liverpoolMoves2.crop(2,2);
        liverpoolRunningWithBallN4 = liverpoolMoves2.crop(2,3);
        liverpoolRunningWithBallS1 = liverpoolMoves2.crop(3,0);
        liverpoolRunningWithBallS2 = liverpoolMoves2.crop(3,1);
        liverpoolRunningWithBallS3 = liverpoolMoves2.crop(3,2);
        liverpoolRunningWithBallS4 = liverpoolMoves2.crop(3,3);
        liverpoolRunningWithBallNE1 = liverpoolMoves2.crop(1,3);
        liverpoolRunningWithBallNE2 = liverpoolMoves2.crop(1,0);
        liverpoolRunningWithBallNE3 = liverpoolMoves2.crop(1,1);
        liverpoolRunningWithBallNE4 = liverpoolMoves2.crop(1,2);
        liverpoolRunningWithBallSE1 = liverpoolMoves1.crop(3,3);
        liverpoolRunningWithBallSE2 = liverpoolMoves1.crop(3,0);
        liverpoolRunningWithBallSE3 = liverpoolMoves1.crop(3,1);
        liverpoolRunningWithBallSE4 = liverpoolMoves1.crop(3,2);
        liverpoolRunningWithBallNW1 = liverpoolMoves2.crop(0,0);
        liverpoolRunningWithBallNW2 = liverpoolMoves2.crop(0,1);
        liverpoolRunningWithBallNW3 = liverpoolMoves2.crop(0,2);
        liverpoolRunningWithBallNW4 = liverpoolMoves2.crop(0,3);
        liverpoolRunningWithBallSW1 = liverpoolMoves1.crop(2,0);
        liverpoolRunningWithBallSW2 = liverpoolMoves1.crop(2,1);
        liverpoolRunningWithBallSW3 = liverpoolMoves1.crop(2,2);
        liverpoolRunningWithBallSW4 = liverpoolMoves1.crop(2,3);

        liverpoolRunningWithoutBallW1 = liverpoolMoves3.crop(0,0);
        liverpoolRunningWithoutBallW2 = liverpoolMoves3.crop(0,3);
        liverpoolRunningWithoutBallW3 = liverpoolMoves3.crop(0,2);
        liverpoolRunningWithoutBallW4 = liverpoolMoves3.crop(0,1);
        liverpoolRunningWithoutBallE1 = liverpoolMoves3.crop(1,3);
        liverpoolRunningWithoutBallE2 = liverpoolMoves3.crop(1,0);
        liverpoolRunningWithoutBallE3 = liverpoolMoves3.crop(1,1);
        liverpoolRunningWithoutBallE4 = liverpoolMoves3.crop(1,2);
        liverpoolRunningWithoutBallN1 = liverpoolMoves4.crop(2,0);
        liverpoolRunningWithoutBallN2 = liverpoolMoves4.crop(2,1);
        liverpoolRunningWithoutBallN3 = liverpoolMoves4.crop(2,2);
        liverpoolRunningWithoutBallN4 = liverpoolMoves4.crop(2,3);
        liverpoolRunningWithoutBallS1 = liverpoolMoves4.crop(3,0);
        liverpoolRunningWithoutBallS2 = liverpoolMoves4.crop(3,1);
        liverpoolRunningWithoutBallS3 = liverpoolMoves4.crop(3,2);
        liverpoolRunningWithoutBallS4 = liverpoolMoves4.crop(3,3);
        liverpoolRunningWithoutBallNE1 = liverpoolMoves4.crop(1,3);
        liverpoolRunningWithoutBallNE2 = liverpoolMoves4.crop(1,0);
        liverpoolRunningWithoutBallNE3 = liverpoolMoves4.crop(1,1);
        liverpoolRunningWithoutBallNE4 = liverpoolMoves4.crop(1,2);
        liverpoolRunningWithoutBallSE1 = liverpoolMoves3.crop(3,3);
        liverpoolRunningWithoutBallSE2 = liverpoolMoves3.crop(3,0);
        liverpoolRunningWithoutBallSE3 = liverpoolMoves3.crop(3,1);
        liverpoolRunningWithoutBallSE4 = liverpoolMoves3.crop(3,2);
        liverpoolRunningWithoutBallNW1 = liverpoolMoves4.crop(0,0);
        liverpoolRunningWithoutBallNW2 = liverpoolMoves4.crop(0,1);
        liverpoolRunningWithoutBallNW3 = liverpoolMoves4.crop(0,2);
        liverpoolRunningWithoutBallNW4 = liverpoolMoves4.crop(0,3);
        liverpoolRunningWithoutBallSW1 = liverpoolMoves3.crop(2,0);
        liverpoolRunningWithoutBallSW2 = liverpoolMoves3.crop(2,1);
        liverpoolRunningWithoutBallSW3 = liverpoolMoves3.crop(2,2);
        liverpoolRunningWithoutBallSW4 = liverpoolMoves3.crop(2,3);

        arsenalPassE = arsenalSpecialMoves.crop(0,0);
        arsenalPassW = arsenalSpecialMoves.crop(0,1);
        arsenalPassS = arsenalSpecialMoves.crop(1,0);
        arsenalPassN = arsenalSpecialMoves.crop(1,1);
        arsenalPassNE = arsenalSpecialMoves.crop(1,2);
        arsenalPassNW = arsenalSpecialMoves.crop(1,3);
        arsenalPassSE = arsenalSpecialMoves.crop(0,2);
        arsenalPassSW = arsenalSpecialMoves.crop(0,3);
        arsenaltackleNE = arsenalSpecialMoves.crop(2,1);
        arsenaltackleNW = arsenalSpecialMoves.crop(2,0);
        arsenaltackleSE = arsenalSpecialMoves.crop(2,2);
        arsenaltackleSW = arsenalSpecialMoves.crop(2,3);
        arsenalWait1 = arsenalSpecialMoves.crop(3,0);
        arsenalWait2 = arsenalSpecialMoves.crop(3,1);

        chelseaPassE = chelseaSpecialMoves.crop(0,0);
        chelseaPassW = chelseaSpecialMoves.crop(0,1);
        chelseaPassS = chelseaSpecialMoves.crop(1,0);
        chelseaPassN = chelseaSpecialMoves.crop(1,1);
        chelseaPassNE = chelseaSpecialMoves.crop(1,2);
        chelseaPassNW = chelseaSpecialMoves.crop(1,3);
        chelseaPassSE = chelseaSpecialMoves.crop(0,2);
        chelseaPassSW = chelseaSpecialMoves.crop(0,3);
        chelseatackleNE = chelseaSpecialMoves.crop(2,1);
        chelseatackleNW = chelseaSpecialMoves.crop(2,0);
        chelseatackleSE = chelseaSpecialMoves.crop(2,2);
        chelseatackleSW = chelseaSpecialMoves.crop(2,3);
        chelseaWait1 = chelseaSpecialMoves.crop(3,0);
        chelseaWait2 = chelseaSpecialMoves.crop(3,1);

        manCityPassE = manCitySpecialMoves.crop(0,0);
        manCityPassW = manCitySpecialMoves.crop(0,1);
        manCityPassS = manCitySpecialMoves.crop(1,0);
        manCityPassN = manCitySpecialMoves.crop(1,1);
        manCityPassNE = manCitySpecialMoves.crop(1,2);
        manCityPassNW = manCitySpecialMoves.crop(1,3);
        manCityPassSE = manCitySpecialMoves.crop(0,2);
        manCityPassSW = manCitySpecialMoves.crop(0,3);
        manCitytackleNE = manCitySpecialMoves.crop(2,1);
        manCitytackleNW = manCitySpecialMoves.crop(2,0);
        manCitytackleSE = manCitySpecialMoves.crop(2,2);
        manCitytackleSW = manCitySpecialMoves.crop(2,3);
        manCityWait1 = manCitySpecialMoves.crop(3,0);
        manCityWait2 = manCitySpecialMoves.crop(3,1);

        liverpoolPassE = liverpoolSpecialMoves.crop(0,0);
        liverpoolPassW = liverpoolSpecialMoves.crop(0,1);
        liverpoolPassS = liverpoolSpecialMoves.crop(1,0);
        liverpoolPassN = liverpoolSpecialMoves.crop(1,1);
        liverpoolPassNE = liverpoolSpecialMoves.crop(1,2);
        liverpoolPassNW = liverpoolSpecialMoves.crop(1,3);
        liverpoolPassSE = liverpoolSpecialMoves.crop(0,2);
        liverpoolPassSW = liverpoolSpecialMoves.crop(0,3);
        liverpooltackleNE = liverpoolSpecialMoves.crop(2,1);
        liverpooltackleNW = liverpoolSpecialMoves.crop(2,0);
        liverpooltackleSE = liverpoolSpecialMoves.crop(2,2);
        liverpooltackleSW = liverpoolSpecialMoves.crop(2,3);
        liverpoolWait1 = liverpoolSpecialMoves.crop(3,0);
        liverpoolWait2 = liverpoolSpecialMoves.crop(3,1);


        heroRight4=fotbal.crop(3,1);
        heroRight41=fotbal.crop(2,1);
        heroRight42=fotbal.crop(1,1);
        heroRight43=fotbal.crop(0,1);

        heroLeft4=fotbal.crop(0,0);
        heroLeft41=fotbal.crop(1,0);
        heroLeft42=fotbal.crop(2,0);
        heroLeft43=fotbal.crop(3,0);

        block4=fotbal.crop(0,0);

        corner = utilities.crop(0,0);
        cursor = utilities.crop(0,1);

        ball1 = ball.crop(0,0);
        ball2 = ball.crop(0,1);
        ball3 = ball.crop(0,2);
        ball4 = ball.crop(0,3);
        ball5 = ball.crop(1,0);
        ball6 = ball.crop(1,1);
        ball7 = ball.crop(1,2);
        ball8 = ball.crop(1,3);
        ball9 = ball.crop(2,0);

        lights = ImageLoader.LoadImage("/textures/NocturneLights.png");

        staff1 = ImageLoader.LoadImage("/textures/Staff/Staff1.png");
        staff2 = ImageLoader.LoadImage("/textures/Staff/Staff2.png");
        staff3 = ImageLoader.LoadImage("/textures/Staff/Staff3.png");
        staff4 = ImageLoader.LoadImage("/textures/Staff/Staff4.png");
        staff5 = ImageLoader.LoadImage("/textures/Staff/Staff5.png");
        staff6 = ImageLoader.LoadImage("/textures/Staff/Staff6.png");
        staff7 = ImageLoader.LoadImage("/textures/Staff/Staff7.png");
        staff8 = ImageLoader.LoadImage("/textures/Staff/Staff8.png");
        staff9 = ImageLoader.LoadImage("/textures/Staff/Staff9.png");
        staff10 = ImageLoader.LoadImage("/textures/Staff/Staff10.png");
        staff11 = ImageLoader.LoadImage("/textures/Staff/Staff11.png");
        staff12 = ImageLoader.LoadImage("/textures/Staff/Staff12.png");
        staff13 = ImageLoader.LoadImage("/textures/Staff/Staff13.png");
        staff14 = ImageLoader.LoadImage("/textures/Staff/Staff14.png");
        staff15 = ImageLoader.LoadImage("/textures/Staff/Staff15.png");
        staff16 = ImageLoader.LoadImage("/textures/Staff/Staff16.png");
        staff17 = ImageLoader.LoadImage("/textures/Staff/Staff17.png");
        staff18 = ImageLoader.LoadImage("/textures/Staff/Staff18.png");
        staff19 = ImageLoader.LoadImage("/textures/Staff/Staff19.png");
        staff20 = ImageLoader.LoadImage("/textures/Staff/Staff20.png");
        staff21 = ImageLoader.LoadImage("/textures/Staff/Staff21.png");
        staff22 = ImageLoader.LoadImage("/textures/Staff/Staff22.png");
        staff23 = ImageLoader.LoadImage("/textures/Staff/Staff23.png");
        staff24 = ImageLoader.LoadImage("/textures/Staff/Staff24.png");
        staff25 = ImageLoader.LoadImage("/textures/Staff/Staff25.png");
        staff26 = ImageLoader.LoadImage("/textures/Staff/Staff26.png");
        staff27 = ImageLoader.LoadImage("/textures/Staff/Staff27.png");
        staff28 = ImageLoader.LoadImage("/textures/Staff/Staff28.png");
        staff29 = ImageLoader.LoadImage("/textures/Staff/Staff29.png");
        staff30 = ImageLoader.LoadImage("/textures/Staff/Staff30.png");
        staff31 = ImageLoader.LoadImage("/textures/Staff/Staff31.png");
        staff32 = ImageLoader.LoadImage("/textures/Staff/Staff32.png");
        staff33 = ImageLoader.LoadImage("/textures/Staff/Staff33.png");
        staff34 = ImageLoader.LoadImage("/textures/Staff/Staff34.png");
        staff35 = ImageLoader.LoadImage("/textures/Staff/Staff35.png");
        staff36 = ImageLoader.LoadImage("/textures/Staff/Staff36.png");
        staff37 = ImageLoader.LoadImage("/textures/Staff/Staff37.png");
        staff38 = ImageLoader.LoadImage("/textures/Staff/Staff38.png");
        staff39 = ImageLoader.LoadImage("/textures/Staff/Staff39.png");
        staff40 = ImageLoader.LoadImage("/textures/Staff/Staff40.png");
        staff41 = ImageLoader.LoadImage("/textures/Staff/Staff41.png");
        staff42 = ImageLoader.LoadImage("/textures/Staff/Staff42.png");
        staff43 = ImageLoader.LoadImage("/textures/Staff/Staff43.png");
        staff44 = ImageLoader.LoadImage("/textures/Staff/Staff44.png");
        staff45 = ImageLoader.LoadImage("/textures/Staff/Staff45.png");
        staff46 = ImageLoader.LoadImage("/textures/Staff/Staff46.png");
        staff47 = ImageLoader.LoadImage("/textures/Staff/Staff47.png");
        staff48 = ImageLoader.LoadImage("/textures/Staff/Staff48.png");
        staff49 = ImageLoader.LoadImage("/textures/Staff/Staff49.png");

        tribune_Red = ImageLoader.LoadImage("/textures/Stadiums/Tribune_Red.png");
        tribune_Blue = ImageLoader.LoadImage("/textures/Stadiums/Tribune_Blue.png");
        tribune_Arsenal1 = ImageLoader.LoadImage("/textures/Stadiums/Arsenal1.png");
        tribune_Arsenal2 = ImageLoader.LoadImage("/textures/Stadiums/Arsenal2.png");
        tribune_Arsenal3 = ImageLoader.LoadImage("/textures/Stadiums/Arsenal3.png");
        tribune_Arsenal4 = ImageLoader.LoadImage("/textures/Stadiums/Arsenal4.png");
        tribune_Arsenal5 = ImageLoader.LoadImage("/textures/Stadiums/Arsenal5.png");
        tribune_Arsenal6 = ImageLoader.LoadImage("/textures/Stadiums/Arsenal6.png");
        tribune_Chelsea1 = ImageLoader.LoadImage("/textures/Stadiums/Chelsea1.png");
        tribune_Chelsea2 = ImageLoader.LoadImage("/textures/Stadiums/Chelsea2.png");
        tribune_Chelsea3 = ImageLoader.LoadImage("/textures/Stadiums/Chelsea3.png");
        tribune_Chelsea4 = ImageLoader.LoadImage("/textures/Stadiums/Chelsea4.png");
        tribune_Chelsea5 = ImageLoader.LoadImage("/textures/Stadiums/Chelsea5.png");
        tribune_Chelsea6 = ImageLoader.LoadImage("/textures/Stadiums/Chelsea6.png");
        tribune_Liverpool1 = ImageLoader.LoadImage("/textures/Stadiums/Liverpool1.png");
        tribune_Liverpool2 = ImageLoader.LoadImage("/textures/Stadiums/Liverpool2.png");
        tribune_Liverpool3 = ImageLoader.LoadImage("/textures/Stadiums/Liverpool3.png");
        tribune_Liverpool4 = ImageLoader.LoadImage("/textures/Stadiums/Liverpool4.png");
        tribune_Liverpool5 = ImageLoader.LoadImage("/textures/Stadiums/Liverpool5.png");
        tribune_Liverpool6 = ImageLoader.LoadImage("/textures/Stadiums/Liverpool6.png");
        tribune_ManCity1 = ImageLoader.LoadImage("/textures/Stadiums/ManCity1.png");
        tribune_ManCity2 = ImageLoader.LoadImage("/textures/Stadiums/ManCity2.png");
        tribune_ManCity3 = ImageLoader.LoadImage("/textures/Stadiums/ManCity3.png");
        tribune_ManCity4 = ImageLoader.LoadImage("/textures/Stadiums/ManCity4.png");
        tribune_ManCity5 = ImageLoader.LoadImage("/textures/Stadiums/ManCity5.png");
        tribune_ManCity6 = ImageLoader.LoadImage("/textures/Stadiums/ManCity6.png");

         controls = ImageLoader.LoadImage("/textures/Main Menu/Controls.png");
         controlsEnter = ImageLoader.LoadImage("/textures/Main Menu/Controls_Enter.png");
         graphicsSettings = ImageLoader.LoadImage("/textures/Main Menu/Graphics.png");
         graphicsHigh = ImageLoader.LoadImage("/textures/Main Menu/Graphics High.png");
         graphicsLow = ImageLoader.LoadImage("/textures/Main Menu/Graphics Low.png");

        P1_Arsenal = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal1.png");
        P1_Arsenal_Chelsea = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_Chelsea.png");
        P1_Arsenal_Chelsea_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_Chelsea - Reverse.png");
        P1_Arsenal_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_Enter.png");
        P1_Arsenal_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_Enter2.png");
        P1_Arsenal_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_Enter3.png");
        P1_Arsenal_P2_Arsenal = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Arsenal.png");
        P1_Arsenal_P2_Arsenal_Chelsea = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Arsenal_Chelsea.png");
        P1_Arsenal_P2_Arsenal_Chelsea_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Arsenal_Chelsea - Reverse.png");
        P1_Arsenal_P2_Arsenal_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Arsenal_Enter.png");
        P1_Arsenal_P2_Chelsea = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Chelsea.png");
        P1_Arsenal_P2_Chelsea_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Chelsea_Enter.png");
        P1_Arsenal_P2_Chelsea_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Chelsea_Enter2.png");
        P1_Arsenal_P2_Chelsea_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Chelsea_Enter3.png");
        P1_Arsenal_P2_Chelsea_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Chelsea_Enter4.png");
        P1_Arsenal_P2_Chelsea_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Chelsea_Enter5.png");
        P1_Arsenal_P2_Chelsea_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Chelsea_Enter6.png");
        P1_Arsenal_P2_Chelsea_Liverpool = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Chelsea_Liverpool.png");
        P1_Arsenal_P2_Chelsea_Liverpool_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Chelsea_Liverpool - Reverse.png");
        P1_Arsenal_P2_Liverpool = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Liverpool.png");
        P1_Arsenal_P2_Liverpool_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Liverpool_Enter.png");
        P1_Arsenal_P2_Liverpool_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Liverpool_Enter2.png");
        P1_Arsenal_P2_Liverpool_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Liverpool_Enter3.png");
        P1_Arsenal_P2_Liverpool_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Liverpool_Enter4.png");
        P1_Arsenal_P2_Liverpool_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Liverpool_Enter5.png");
        P1_Arsenal_P2_Liverpool_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Liverpool_Enter6.png");
        P1_Arsenal_P2_Liverpool_ManCity = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Liverpool_ManCity.png");
        P1_Arsenal_P2_Liverpool_ManCity_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_Liverpool_ManCity - Reverse.png");
        P1_Arsenal_P2_ManCity = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_ManCity.png");
        P1_Arsenal_P2_ManCity_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_ManCity_Enter.png");
        P1_Arsenal_P2_ManCity_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_ManCity_Enter2.png");
        P1_Arsenal_P2_ManCity_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_ManCity_Enter3.png");
        P1_Arsenal_P2_ManCity_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_ManCity_Enter4.png");
        P1_Arsenal_P2_ManCity_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_ManCity_Enter5.png");
        P1_Arsenal_P2_ManCity_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_Arsenal_P2_ManCity_Enter6.png");
        P1_Chelsea = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea.png");
        P1_Chelsea_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_Enter.png");
        P1_Chelsea_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_Enter2.png");
        P1_Chelsea_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_Enter3.png");
        P1_Chelsea_Liverpool = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_Liverpool.png");
        P1_Chelsea_Liverpool_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_Liverpool - Reverse.png");
        P1_Chelsea_P2_Arsenal = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Arsenal.png");
        P1_Chelsea_P2_Arsenal_Chelsea = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Arsenal_Chelsea.png");
        P1_Chelsea_P2_Arsenal_Chelsea_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Arsenal_Chelsea - Reverse.png");
        P1_Chelsea_P2_Arsenal_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Arsenal_Enter.png");
        P1_Chelsea_P2_Arsenal_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Arsenal_Enter2.png");
        P1_Chelsea_P2_Arsenal_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Arsenal_Enter3.png");
        P1_Chelsea_P2_Arsenal_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Arsenal_Enter4.png");
        P1_Chelsea_P2_Arsenal_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Arsenal_Enter5.png");
        P1_Chelsea_P2_Arsenal_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Arsenal_Enter6.png");
        P1_Chelsea_P2_Chelsea = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Chelsea.png");
        P1_Chelsea_P2_Chelsea_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Chelsea_Enter.png");
        P1_Chelsea_P2_Chelsea_Liverpool = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Chelsea_Liverpool.png");
        P1_Chelsea_P2_Chelsea_Liverpool_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Chelsea_Liverpool - Reverse.png");
        P1_Chelsea_P2_Liverpool = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Liverpool.png");
        P1_Chelsea_P2_Liverpool_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Liverpool_Enter.png");
        P1_Chelsea_P2_Liverpool_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Liverpool_Enter2.png");
        P1_Chelsea_P2_Liverpool_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Liverpool_Enter3.png");
        P1_Chelsea_P2_Liverpool_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Liverpool_Enter4.png");
        P1_Chelsea_P2_Liverpool_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Liverpool_Enter5.png");
        P1_Chelsea_P2_Liverpool_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Liverpool_Enter6.png");
        P1_Chelsea_P2_Liverpool_ManCity = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Liverpool_ManCity.png");
        P1_Chelsea_P2_Liverpool_ManCity_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_Liverpool_ManCity - Reverse.png");
        P1_Chelsea_P2_ManCity = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_ManCity.png");
        P1_Chelsea_P2_ManCity_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_ManCity_Enter.png");
        P1_Chelsea_P2_ManCity_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_ManCity_Enter2.png");
        P1_Chelsea_P2_ManCity_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_ManCity_Enter3.png");
        P1_Chelsea_P2_ManCity_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_ManCity_Enter4.png");
        P1_Chelsea_P2_ManCity_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_ManCity_Enter5.png");
        P1_Chelsea_P2_ManCity_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_Chelsea_P2_ManCity_Enter6.png");
        P1_Liverpool = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool.png");
        P1_Liverpool_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_Enter.png");
        P1_Liverpool_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_Enter2.png");
        P1_Liverpool_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_Enter3.png");
        P1_Liverpool_ManCity = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_ManCity.png");
        P1_Liverpool_ManCity_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_ManCity - Reverse.png");
        P1_Liverpool_P2_Arsenal = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Arsenal.png");
        P1_Liverpool_P2_Arsenal_Chelsea = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Arsenal_Chelsea.png");
        P1_Liverpool_P2_Arsenal_Chelsea_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Arsenal_Chelsea - Reverse.png");
        P1_Liverpool_P2_Arsenal_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Arsenal_Enter.png");
        P1_Liverpool_P2_Arsenal_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Arsenal_Enter2.png");
        P1_Liverpool_P2_Arsenal_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Arsenal_Enter3.png");
        P1_Liverpool_P2_Arsenal_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Arsenal_Enter4.png");
        P1_Liverpool_P2_Arsenal_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Arsenal_Enter5.png");
        P1_Liverpool_P2_Arsenal_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Arsenal_Enter6.png");
        P1_Liverpool_P2_Chelsea = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Chelsea.png");
        P1_Liverpool_P2_Chelsea_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Chelsea_Enter.png");
        P1_Liverpool_P2_Chelsea_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Chelsea_Enter2.png");
        P1_Liverpool_P2_Chelsea_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Chelsea_Enter3.png");
        P1_Liverpool_P2_Chelsea_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Chelsea_Enter4.png");
        P1_Liverpool_P2_Chelsea_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Chelsea_Enter5.png");
        P1_Liverpool_P2_Chelsea_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Chelsea_Enter6.png");
        P1_Liverpool_P2_Chelsea_Liverpool = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Chelsea_Liverpool.png");
        P1_Liverpool_P2_Chelsea_Liverpool_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Chelsea_Liverpool - Reverse.png");
        P1_Liverpool_P2_Liverpool = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Liverpool.png");
        P1_Liverpool_P2_Liverpool_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Liverpool_Enter.png");
        P1_Liverpool_P2_Liverpool_ManCity = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Liverpool_ManCity.png");
        P1_Liverpool_P2_Liverpool_ManCity_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_Liverpool_ManCity - Reverse.png");
        P1_Liverpool_P2_ManCity = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_ManCity.png");
        P1_Liverpool_P2_ManCity_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_ManCity_Enter.png");
        P1_Liverpool_P2_ManCity_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_ManCity_Enter2.png");
        P1_Liverpool_P2_ManCity_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_ManCity_Enter3.png");
        P1_Liverpool_P2_ManCity_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_ManCity_Enter4.png");
        P1_Liverpool_P2_ManCity_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_ManCity_Enter5.png");
        P1_Liverpool_P2_ManCity_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_Liverpool_P2_ManCity_Enter6.png");
        P1_ManCity = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity.png");
        P1_ManCity_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_Enter.png");
        P1_ManCity_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_Enter2.png");
        P1_ManCity_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_Enter3.png");
        P1_ManCity_P2_Arsenal = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Arsenal.png");
        P1_ManCity_P2_Arsenal_Chelsea = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Arsenal_Chelsea.png");
        P1_ManCity_P2_Arsenal_Chelsea_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Arsenal_Chelsea - Reverse.png");
        P1_ManCity_P2_Arsenal_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Arsenal_Enter.png");
        P1_ManCity_P2_Arsenal_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Arsenal_Enter2.png");
        P1_ManCity_P2_Arsenal_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Arsenal_Enter3.png");
        P1_ManCity_P2_Arsenal_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Arsenal_Enter4.png");
        P1_ManCity_P2_Arsenal_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Arsenal_Enter5.png");
        P1_ManCity_P2_Arsenal_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Arsenal_Enter6.png");
        P1_ManCity_P2_Chelsea = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Chelsea.png");
        P1_ManCity_P2_Chelsea_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Chelsea_Enter.png");
        P1_ManCity_P2_Chelsea_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Chelsea_Enter2.png");
        P1_ManCity_P2_Chelsea_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Chelsea_Enter3.png");
        P1_ManCity_P2_Chelsea_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Chelsea_Enter4.png");
        P1_ManCity_P2_Chelsea_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Chelsea_Enter5.png");
        P1_ManCity_P2_Chelsea_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Chelsea_Enter6.png");
        P1_ManCity_P2_Chelsea_Liverpool = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Chelsea_Liverpool.png");
        P1_ManCity_P2_Chelsea_Liverpool_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Chelsea_Liverpool - Reverse.png");
        P1_ManCity_P2_Liverpool = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Liverpool.png");
        P1_ManCity_P2_Liverpool_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Liverpool_Enter.png");
        P1_ManCity_P2_Liverpool_Enter2 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Liverpool_Enter2.png");
        P1_ManCity_P2_Liverpool_Enter3 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Liverpool_Enter3.png");
        P1_ManCity_P2_Liverpool_Enter4 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Liverpool_Enter4.png");
        P1_ManCity_P2_Liverpool_Enter5 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Liverpool_Enter5.png");
        P1_ManCity_P2_Liverpool_Enter6 = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Liverpool_Enter6.png");
        P1_ManCity_P2_Liverpool_ManCity = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Liverpool_ManCity.png");
        P1_ManCity_P2_Liverpool_ManCity_Reverse = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_Liverpool_ManCity - Reverse.png");
        P1_ManCity_P2_ManCity = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_ManCity.png");
        P1_ManCity_P2_ManCity_Enter = ImageLoader.LoadImage("/textures/Match Menu/P1_ManCity_P2_ManCity_Enter.png");
    }
}
